services:
  # ===================== BANDRED =====================
  bandred-app:
    build: ./bandred
    container_name: bandred-app
    ports:
      - "9091:9091"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 9091
      DB_URL: jdbc:postgresql://172.30.10.4:5432/bandred_db
      DB_USER: postgres
      DB_PASS: EpmapaT2025
      PAGOSONLINE_API_BASE_URL: http://pagosonline-app:9092
      ERP_BACKEND_BASE_URL: http://192.168.0.165:9080/fec_factura
    networks:
      - epmapat-network

  # ===================== EMAILS =====================
  emails-app:
    build: ./emails
    container_name: emails-app
    ports:
      - "9099:9099"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 9099
      DB_URL: jdbc:postgresql://172.30.10.4:5432/emails_db
      DB_USER: postgres
      DB_PASS: EpmapaT2025
    env_file:
      - emails/.env
    networks:
      - epmapat-network

  # ===================== EPMAPAAPI =====================
  epmapaapi-app:
    build: ./epmapaapi
    container_name: epmapaapi-app
    ports:
      - "9085:8080"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 8080
      DB_URL: jdbc:postgresql://172.30.10.4:5432/ErpEpmapaT
      DB_USER: postgres
      DB_PASS: EpmapaT2025
    networks:
      - epmapat-network

  # ===================== PAGOSONLINE =====================
  pagosonline-app:
    build: ./pagosonline
    container_name: pagosonline-app
    ports:
      - "32:32"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 32
      DB_URL: jdbc:postgresql://172.30.10.4:5432/pagosonline_db
      DB_USER: postgres
      DB_PASS: EpmapaT2025
      PAGOSONLINE_API_BASE_URL: http://localhost:32
      ERP_BACKEND_BASE_URL: http://192.168.0.165:9080/fec_factura
    networks:
      - epmapat-network

  # ===================== SRI-FILES =====================
  sri-app:
    build: ./sri-files
    container_name: sri-app
    ports:
      - "9090:9090"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 9090
      DB_URL: jdbc:postgresql://172.30.10.4:5432/sri_files_db
      DB_USER: postgres
      DB_PASS: EpmapaT2025
      ERP_BACKEND_BASE_URL: http://192.168.0.165:9080
      EMAIL_MS_BASE_URL: http://emails-app:9099
    networks:
      - epmapat-network

networks:
  epmapat-network:
    external: true
