services:
  app:
    build: .
    container_name: bandred-app
    ports:
      - "9091:9091"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 9091
      DB_URL: jdbc:postgresql://172.30.10.4:5432/bandred_db
      DB_USER: postgres
      DB_PASS: EpmapaT2025
      PAGOSONLINE_API_BASE_URL: http://pagosonline:9092
      ERP_BACKEND_BASE_URL: http://192.168.0.165:9080/fec_factura
    networks:
      - epmapat-network

networks:
  epmapat-network:
    external: true
