ALTER TABLE empresa
    ADD COLUMN IF NOT EXISTS correo_nombre_remitente VARCHAR(255),
    ADD COLUMN IF NOT EXISTS correo_enviar_xml BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS correo_enviar_ride BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS correo_plantilla_asunto VARCHAR(255),
    ADD COLUMN IF NOT EXISTS certificado_activo BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS sri_timeout_conexion_ms INTEGER NOT NULL DEFAULT 10000,
    ADD COLUMN IF NOT EXISTS sri_timeout_respuesta_ms INTEGER NOT NULL DEFAULT 30000,
    ADD COLUMN IF NOT EXISTS sri_max_reintentos INTEGER NOT NULL DEFAULT 5;
