package com.erp.sri_files.domain.documento;

public enum DocumentoEstado {
    RECIBIDO,
    VALIDANDO,
    VALIDADO,
    XML_GENERADO,
    FIRMADO,
    ENVIANDO_SRI,
    RECIBIDO_SRI,
    PENDIENTE_AUTORIZACION,
    AUTORIZADO,
    RIDE_GENERADO,
    CORREO_PENDIENTE,
    CORREO_ENVIADO,
    FINALIZADO,
    ERROR_VALIDACION,
    ERROR_XML,
    ERROR_FIRMA,
    DEVUELTO_SRI,
    NO_AUTORIZADO,
    ERROR_ENVIO_SRI,
    ERROR_AUTORIZACION,
    ERROR_RIDE,
    ERROR_CORREO,
    REQUIERE_INTERVENCION,
    CANCELADO
}
