services:
  app:
    build: .
    container_name: sri-app
    ports:
      - "9090:9090"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 9090
      DB_URL: jdbc:postgresql://172.30.10.4:5432/sri_files_db
      DB_USER: postgres
      DB_PASS: EpmapaT2025
      ERP_BACKEND_BASE_URL: http://192.168.0.165:9080
      EMAIL_MS_BASE_URL: http://emails:9099
    networks:
      - epmapat-network

networks:
  epmapat-network:
    external: true
