services:
  postgres:
    image: postgres:16
    container_name: emails-postgres
    environment:
      POSTGRES_DB: emails_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Guayaquil
    volumes:
      - emails-postgres-data:/var/lib/postgresql/data
    networks:
      - epmapat-network

  app:
    build: .
    container_name: emails-app
    ports:
      - "9099:9099"
    environment:
      TZ: America/Guayaquil
      SERVER_PORT: 9099
      DB_URL: jdbc:postgresql://postgres:5432/emails_db
      DB_USER: postgres
      DB_PASS: postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - epmapat-network

volumes:
  emails-postgres-data:

networks:
  epmapat-network:
    external: true
